version: "3.0"
services:
  movies:
    working_dir: /go/src/github.com/ceiba-meli-demo/movies
    build:
      context: ./movies
    volumes:
      - ./movies:/go/src/github.com/ceiba-meli-demo/movies
    command: go run .
    depends_on:
      - mongodb
    environment:
      PORT: ${MOVIES_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  mongodb:
    image: mongo:4.0-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
