version: "3.0"
services:
  movies:
    working_dir: /go/src/github.com/ceiba-meli-demo/movies
    build:
      context: ./movies
    volumes:
      - ./movies:/go/src/github.com/ceiba-meli-demo/movies
    command: go run main.go
    depends_on:
      - mongodb
    environment:
      PORT: ${MOVIES_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
    networks:
      - movies-network
      - shared-network
    ports:
      - "${MOVIES_PORT}:8081"

  users:
    working_dir: /go/src/github.com/ceiba-meli-demo/users
    restart: on-failure
    build:
      context: ./users
    volumes:
      - ./users:/go/src/github.com/ceiba-meli-demo/users
    # command: go run .
    depends_on:
      - postgres
    environment:
      PORT: ${USERS_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - users-network
      - shared-network
    ports:
      - "${USERS_PORT}:8086"

  mongodb:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - movies-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - 5432:5432
    networks:
      - users-network

networks:
  users-network:
    driver: bridge
  movies-network:
    driver: bridge
  shared-network:
    driver: bridge
